name: Expense Tracker CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Stop Old Container (If Running)
        run: |
          docker stop skills-utilization-app || true
          docker rm skills-utilization-app || true

      - name: Build Docker Image
        run: docker build -t skills-utilization .

      - name: Run Application Container
        run: docker run -d --name skills-utilization-app -p 5000:5000 skills-utilization
